services:
  nginx:
    image: nginx:alpine
    container_name: wpp-deployer-nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
